apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: react
      image: node:alpine3.12
    - name: docker
      image: docker:18.06.1
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        - path: /var/run/docker.sock
